name: Tests

on:
    pull_request:
        types: [opened, synchronize, reopened, labeled]
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up Node.js lts
              uses: actions/setup-node@v2
              with:
                  node-version: "20"
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
